//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETENTITYFrameworkHWK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Car
    {
        public int Id { get; set; }
        [DisplayName("Car Name")]
        public string CarName { get; set; }
        [DisplayName("Car Colour")]
        public string CarColour { get; set; }
        [DisplayName("Car Size")]
        public string CarSize { get; set; }
        [DisplayName("Car Engine Size")]
        public string CarEngineSize { get; set; }
    }
}
