//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETENTITYFrameworkHWK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Manufacturer
    {
        public int Id { get; set; }
        [DisplayName("Manufacturer Name")]
        public string ManfucatorName { get; set; }
        [DisplayName("Manufacturer Location")]
        public string ManufacurerLocation { get; set; }
    }
}
