//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETENTITYFrameworkHWK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MiniBu
    {
        public int Id { get; set; }
        [DisplayName("Manufacturer Name")]
        public string MiniBusMake { get; set; }
        [DisplayName("Colour")]
        public string Colour { get; set; }
        [DisplayName("Number of seats")]
        public Nullable<int> NumberOfSeats { get; set; }
        [DisplayName("Engine size")]
        public Nullable<int> EngineSize { get; set; }
    }
}
