//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETENTITYFrameworkHWK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RentedCar
    {
        public int Id { get; set; }
        [DisplayName("Rented car name")]
        public string RentedCarName { get; set; }
        [DisplayName("Hire Date")]
        public Nullable<System.DateTime> HireDate { get; set; }
        [DisplayName("Duration")]
        public string Duration { get; set; }
        [DisplayName("Rented by")]
        public string RentedBy { get; set; }
    }
}
