//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETENTITYFrameworkHWK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Van
    {
        public int Id { get; set; }
        [DisplayName("Van Make")]
        [Required(ErrorMessage = "Must enter a van make")]
        public string VanMake { get; set; }
        [DisplayName("Van Size")]
        [Required(ErrorMessage = "Must enter a van size")]
        public string VanSize { get; set; }
        [DisplayName("Number of Seats")]
        [Required(ErrorMessage = "Enter Number of seats ")]
        public Nullable<int> NumberOfSeats { get; set; }
        [DisplayName("Van Colour")]
        [Required(ErrorMessage = "Must enter van colour")]
        public string VanColour { get; set; }
    }
}
